// Build a static, same-origin KTX2 transcoder worker from the vendored three.js r170 KTX2Loader + basis_transcoder.js.
// three's KTX2Loader normally assembles this exact source at runtime and starts it from a blob: URL, which would need
// CSP `worker-src blob:`. Shipping it as a file keeps the CSP at 'self'. Output is byte-for-byte what KTX2Loader would
// build (constants, transcoder, worker body).  usage: node tools/showroom/build_ktx2_worker.mjs
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../static/showroom/vendor/three');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ktx2w-'));
try {
  // node resolves the bare 'three' import through a throwaway node_modules next to a copy of the addons
  fs.cpSync(path.join(root, 'addons'), path.join(tmp, 'addons'), { recursive: true });
  const nm = path.join(tmp, 'node_modules', 'three');
  fs.mkdirSync(path.join(nm, 'build'), { recursive: true });
  fs.copyFileSync(path.join(root, 'build', 'three.module.js'), path.join(nm, 'build', 'three.module.js'));
  fs.writeFileSync(path.join(nm, 'package.json'), JSON.stringify({ name: 'three', type: 'module', exports: { '.': './build/three.module.js' } }));
  fs.writeFileSync(path.join(tmp, 'package.json'), JSON.stringify({ type: 'module' }));
  const { KTX2Loader } = await import(pathToFileURL(path.join(tmp, 'addons', 'loaders', 'KTX2Loader.js')).href);
  const transcoder = fs.readFileSync(path.join(root, 'addons', 'libs', 'basis', 'basis_transcoder.js'), 'utf8');
  const fn = KTX2Loader.BasisWorker.toString();
  const body = [
    '/* GENERATED by tools/showroom/build_ktx2_worker.mjs from three@0.170.0 KTX2Loader + basis_transcoder.js. */',
    '/* constants */',
    'let _EngineFormat = ' + JSON.stringify(KTX2Loader.EngineFormat),
    'let _EngineType = ' + JSON.stringify(KTX2Loader.EngineType),
    'let _TranscoderFormat = ' + JSON.stringify(KTX2Loader.TranscoderFormat),
    'let _BasisFormat = ' + JSON.stringify(KTX2Loader.BasisFormat),
    '/* basis_transcoder.js */',
    transcoder,
    '/* worker */',
    fn.substring(fn.indexOf('{') + 1, fn.lastIndexOf('}')),
  ].join('\n');
  const out = path.join(root, 'addons', 'libs', 'basis', 'ktx2_worker.js');
  fs.writeFileSync(out, body);
  console.log('wrote', path.relative(process.cwd(), out), body.length, 'bytes');
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
