// Build the KTX2 (Basis) transcoder as an in-page ES module from the vendored three.js r170 KTX2Loader +
// basis_transcoder.js. three normally runs this code in a Worker started from a blob: URL (CSP `worker-src blob:`).
// A same-origin worker file would avoid blob:, but Firefox does not honour 'wasm-unsafe-eval' inside workers (the
// transcoder's WebAssembly.instantiate is refused unless the worker gets 'unsafe-eval'). Running the identical code
// in the page keeps the CSP exactly as it is. The module wraps the transcoder + the worker body in a function that
// returns a Worker-shaped object (postMessage / addEventListener / terminate) for three's WorkerPool.
// usage: node tools/showroom/build_ktx2_worker.mjs
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// The emscripten (embind) glue builds two kinds of glue functions with Function(): JS invokers for bound C++ functions
// and emval method callers. That needs CSP 'unsafe-eval'. Replace both with emscripten's own closure-based
// equivalents (what -sDYNAMIC_EXECUTION=0 generates), so the transcoder runs under the page's existing CSP.
function noEval(src) {
  const swap = (start, end, replacement) => {
    const i = src.indexOf(start);
    const j = src.indexOf(end, i);
    if (i < 0 || j < 0) throw new Error(`basis_transcoder.js changed: cannot find ${start}`);
    src = src.slice(0, i) + replacement + src.slice(j);
  };
  swap('function craftInvokerFunction(', 'var __embind_register_class_constructor', `function craftInvokerFunction(humanName,argTypes,classType,cppInvokerFunc,cppTargetFunc,isAsync){var argCount=argTypes.length;if(argCount<2){throwBindingError("argTypes array size mismatch! Must at least get return value and 'this' types!")}var isClassMethodFunc=argTypes[1]!==null&&classType!==null;var needsDestructorStack=usesDestructorStack(argTypes);var returns=argTypes[0].name!=="void";var expectedArgCount=argCount-2;var invokerFn=function(...args){if(args.length!==expectedArgCount){throwBindingError("function "+humanName+" called with "+args.length+" arguments, expected "+expectedArgCount)}var destructors=needsDestructorStack?[]:null;var thisWired;var argsWired=[];var invokerArgs=[cppTargetFunc];if(isClassMethodFunc){thisWired=argTypes[1]["toWireType"](destructors,this);invokerArgs.push(thisWired)}for(var i=0;i<expectedArgCount;++i){argsWired[i]=argTypes[i+2]["toWireType"](destructors,args[i]);invokerArgs.push(argsWired[i])}var rv=cppInvokerFunc(...invokerArgs);if(needsDestructorStack){runDestructors(destructors)}else{for(var i=isClassMethodFunc?1:2;i<argTypes.length;i++){var param=i===1?thisWired:argsWired[i-2];if(argTypes[i].destructorFunction!==null){argTypes[i].destructorFunction(param)}}}if(returns){return argTypes[0]["fromWireType"](rv)}};return createNamedFunction(humanName,invokerFn)}`);
  swap('var invokerFunction=newFunc(Function,params)(...args);', 'var functionName=`methodCaller', `var invokerFunction=function(obj,func,destructorsRef,argsPtr){var offset=0;var list=[];if(kind===0){list.push(obj)}for(var i=0;i<argCount;++i){list.push(types[i].readValueFromPointer(argsPtr+offset));offset+=types[i]["argPackAdvance"]}var rv=kind===1?new func(...list):func.call(...list);if(!retType.isVoid){return emval_returnValue(retType,destructorsRef,rv)}};`);
  if (/newFunc\(Function|\beval\(|new Function\b/.test(src)) throw new Error('dynamic code generation left in transcoder');
  return src;
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../static/showroom/vendor/three');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ktx2w-'));
try {
  // node resolves the bare 'three' import through a throwaway node_modules next to a copy of the addons
  fs.cpSync(path.join(root, 'addons'), path.join(tmp, 'addons'), { recursive: true });
  const nm = path.join(tmp, 'node_modules', 'three');
  fs.mkdirSync(path.join(nm, 'build'), { recursive: true });
  fs.copyFileSync(path.join(root, 'build', 'three.module.js'), path.join(nm, 'build', 'three.module.js'));
  fs.writeFileSync(path.join(nm, 'package.json'), JSON.stringify({ name: 'three', type: 'module', exports: { '.': './build/three.module.js' } }));
  fs.writeFileSync(path.join(tmp, 'package.json'), JSON.stringify({ type: 'module' }));
  const { KTX2Loader } = await import(pathToFileURL(path.join(tmp, 'addons', 'loaders', 'KTX2Loader.js')).href);
  const transcoder = noEval(fs.readFileSync(path.join(root, 'addons', 'libs', 'basis', 'basis_transcoder.js'), 'utf8'));
  const fn = KTX2Loader.BasisWorker.toString();
  const body = [
    '/* GENERATED by tools/showroom/build_ktx2_worker.mjs from three@0.170.0 KTX2Loader + basis_transcoder.js. */',
    '/* constants */',
    'let _EngineFormat = ' + JSON.stringify(KTX2Loader.EngineFormat),
    'let _EngineType = ' + JSON.stringify(KTX2Loader.EngineType),
    'let _TranscoderFormat = ' + JSON.stringify(KTX2Loader.TranscoderFormat),
    'let _BasisFormat = ' + JSON.stringify(KTX2Loader.BasisFormat),
    '/* basis_transcoder.js */',
    transcoder,
    '/* worker */',
    fn.substring(fn.indexOf('{') + 1, fn.lastIndexOf('}')),
  ].join('\n');
  const mod = [
    body.replace('/* GENERATED', '/* (inline) GENERATED'),
  ];
  const inline = `/* GENERATED by tools/showroom/build_ktx2_worker.mjs from three@0.170.0 KTX2Loader + basis_transcoder.js. */
export function createInlineTranscoder() {
  const listeners = [];
  const out = [];
  // the worker body talks to "self": messages to it arrive via postMessage below, its replies go to \`out\`
  const self = {
    addEventListener: (type, fn) => { if (type === 'message') listeners.push(fn); },
    postMessage: (data) => { setTimeout(() => { for (const fn of out) fn({ data }); }, 0); },
  };
${mod[0].split('\n').slice(1).join('\n')}
  return {
    postMessage: (data) => { setTimeout(() => { for (const fn of listeners) fn({ data }); }, 0); },
    addEventListener: (type, fn) => { if (type === 'message') out.push(fn); },
    removeEventListener: () => {},
    terminate: () => { listeners.length = 0; out.length = 0; },
  };
}
`;
  const outFile = path.join(root, 'addons', 'libs', 'basis', 'ktx2_inline.js');
  fs.writeFileSync(outFile, inline);
  fs.rmSync(path.join(root, 'addons', 'libs', 'basis', 'ktx2_worker.js'), { force: true });
  console.log('wrote', path.relative(process.cwd(), outFile), inline.length, 'bytes');
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
